# Generated by Django 4.1.2 on 2022-11-03 05:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='checker',
            managers=[
                ('Checker', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contest',
            managers=[
                ('Contest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contest_task',
            managers=[
                ('Contest_task', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contest_user',
            managers=[
                ('Contest_user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='legend',
            managers=[
                ('Legend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='report_sub',
            managers=[
                ('Report_sub', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='review_message',
            managers=[
                ('Review_message', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='submission',
            managers=[
                ('Submission', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('Task', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='test',
            managers=[
                ('Test', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('User', django.db.models.manager.Manager()),
            ],
        ),
    ]
